### ISSUE TITLE
Use a better upped bound (b value) to start the algorithm

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/PlaygroundWithGit.jl#18]
Assuming that `interest_rate` is greater than -1, then the equation that defines the relation between the quantities can be manipulated to show that `i < monthly_payment / borrowed_amount`. Use this ratio instead of `b = 1.0`.

**Comment by datejada** [comment]
I did not know how to include this assumption `interest_rate > -1` (if needed). I have focussed on the whole process (tests, pre-commit, pull-request) since the change in the code was straightforward (I think)
